export type Store = {
  id: string;
  name: string;
  logoGradient: string;
  bannerGradient: string;
  rating: number;
  distance: string;
  deliveryTime: string;
  isOpen: boolean;
  minOrder: string;
  deliveryFee: string;
  description: string;
  tags: string[];
};

export const stores: Store[] = [
  {
    id: "fresh-mart",
    name: "Fresh Mart",
    logoGradient: "from-emerald-500 to-green-600",
    bannerGradient: "from-green-100 via-green-200 to-emerald-100",
    rating: 4.8,
    distance: "2.1 km",
    deliveryTime: "20-30 min",
    isOpen: true,
    minOrder: "₹199",
    deliveryFee: "Free",
    description: "Fresh fruits, vegetables and daily essentials at your doorstep.",
    tags: ["Fast Delivery", "Top Rated"],
  },
  {
    id: "daily-needs",
    name: "Daily Needs",
    logoGradient: "from-blue-500 to-blue-600",
    bannerGradient: "from-blue-100 via-blue-200 to-sky-100",
    rating: 4.5,
    distance: "1.4 km",
    deliveryTime: "15-25 min",
    isOpen: true,
    minOrder: "₹99",
    deliveryFee: "₹20",
    description: "Your one-stop shop for everyday household items and groceries.",
    tags: ["Fast Delivery", "Open Now"],
  },
  {
    id: "green-basket",
    name: "Green Basket",
    logoGradient: "from-lime-500 to-green-600",
    bannerGradient: "from-lime-100 via-green-100 to-emerald-50",
    rating: 4.3,
    distance: "3.2 km",
    deliveryTime: "30-40 min",
    isOpen: true,
    minOrder: "₹149",
    deliveryFee: "Free",
    description: "Organic and farm-fresh produce delivered straight from local farms.",
    tags: ["Free Delivery"],
  },
  {
    id: "nature-fresh",
    name: "Nature Fresh",
    logoGradient: "from-amber-500 to-orange-600",
    bannerGradient: "from-amber-100 via-orange-100 to-yellow-50",
    rating: 4.7,
    distance: "2.8 km",
    deliveryTime: "25-35 min",
    isOpen: true,
    minOrder: "₹249",
    deliveryFee: "Free",
    description: "Premium quality fruits, vegetables and organic dairy products.",
    tags: ["Top Rated", "Free Delivery"],
  },
  {
    id: "city-grocery",
    name: "City Grocery",
    logoGradient: "from-red-500 to-rose-600",
    bannerGradient: "from-red-100 via-rose-100 to-pink-50",
    rating: 4.1,
    distance: "0.8 km",
    deliveryTime: "10-20 min",
    isOpen: true,
    minOrder: "₹99",
    deliveryFee: "₹15",
    description: "Quick grocery delivery for all your urgent kitchen needs.",
    tags: ["Fast Delivery", "Open Now"],
  },
  {
    id: "super-basket",
    name: "Super Basket",
    logoGradient: "from-purple-500 to-violet-600",
    bannerGradient: "from-purple-100 via-violet-100 to-fuchsia-50",
    rating: 4.6,
    distance: "4.1 km",
    deliveryTime: "35-45 min",
    isOpen: false,
    minOrder: "₹299",
    deliveryFee: "Free",
    description: "Wholesale groceries and bulk essentials at the best prices.",
    tags: ["Free Delivery", "Top Rated"],
  },
  {
    id: "reliance-smart",
    name: "Reliance Smart",
    logoGradient: "from-sky-500 to-cyan-600",
    bannerGradient: "from-sky-100 via-cyan-100 to-teal-50",
    rating: 4.4,
    distance: "3.5 km",
    deliveryTime: "25-35 min",
    isOpen: true,
    minOrder: "₹199",
    deliveryFee: "Free",
    description: "Big brand store with a wide range of groceries and home essentials.",
    tags: ["Free Delivery"],
  },
  {
    id: "more-daily",
    name: "More Daily",
    logoGradient: "from-pink-500 to-rose-600",
    bannerGradient: "from-pink-100 via-rose-100 to-red-50",
    rating: 4.2,
    distance: "1.9 km",
    deliveryTime: "20-30 min",
    isOpen: true,
    minOrder: "₹149",
    deliveryFee: "₹10",
    description: "Your neighbourhood store for daily bread, milk and essentials.",
    tags: ["Open Now"],
  },
  {
    id: "organic-hub",
    name: "Organic Hub",
    logoGradient: "from-teal-500 to-emerald-600",
    bannerGradient: "from-teal-100 via-emerald-100 to-green-50",
    rating: 4.9,
    distance: "5.2 km",
    deliveryTime: "40-50 min",
    isOpen: false,
    minOrder: "₹399",
    deliveryFee: "Free",
    description: "100% organic and chemical-free groceries for a healthy lifestyle.",
    tags: ["Top Rated", "Free Delivery"],
  },
  {
    id: "quick-grocery",
    name: "Quick Grocery",
    logoGradient: "from-orange-500 to-amber-600",
    bannerGradient: "from-orange-100 via-amber-100 to-yellow-50",
    rating: 4.0,
    distance: "1.1 km",
    deliveryTime: "10-15 min",
    isOpen: true,
    minOrder: "₹79",
    deliveryFee: "₹25",
    description: "Lightning-fast delivery for urgent grocery needs under 15 minutes.",
    tags: ["Fast Delivery", "Open Now"],
  },
];
